version: '3.2'
services:
  db:
    image: postgres

  web:
    build: .
    command: >
      bash -c "
        mix deps.get &&
        mix deps.compile &&
        mix ecto.create &&
        mix ecto.migrate &&
        mix phx.server
      "
    volumes:
      - .:/myapp
    ports:
      - "4000:4000"
    depends_on:
      - db
